---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: can-mssql-stable
  namespace: tools-argocd
spec:
  project: canaries
  source:
    path: canaries/otel-mssql
    repoURL: git@source.datanerd.us:data-integrations/database-corient-canaries.git
    targetRevision: master
    helm:
      releaseName: mssql-stable
      valueFiles:
        - otel-collector-values.yaml
        - values.yaml
        - values-stable.yaml
      parameters:
        - name: environment
          value: stable
  destination:
    namespace: can-mssql-stable
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
