environment: candidate

nodeSelector:
  role: candidate

nri-bundle:
  global:
    customSecretName: newrelic-licenses-candidate
    customSecretLicenseKey: NRIA_LICENSE_KEY
  newrelic-infrastructure:
    podLabels:
      environment: candidate
    nodeSelector:
      role: candidate
    images:
      agent:
        repository: newrelic/infrastructure-bundle
        tag: a2q-candidate@sha256:bc3d01127c75e4e13b48413a4b64c532f32ed4323aeb0414bc6fc9e290b526e6
        # renovate: datasource=docker depName=newrelic/infrastructure-bundle versioning=docker
        pullPolicy: Always
